import Head from "next/head";
import { Inter } from "next/font/google";
import { Main } from "../components/Main";
import { Header } from "../components/Header";
import { useCallback, useState } from "react";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const [count, setCount] = useState(1);
  const [array, setArray] = useState([]);
  const [text, setText] = useState("");
  const [isShow, setIsShow] = useState(false);
  const [isSmorker, setIsSmorker] = useState(false);
  const handleChange = useCallback((e) => {
    // if (e.target.value.length > 5) {
    //   alert("5文字以内にしてください");
    //   return;
    // }
    setText(e.target.value.trim());
  }, []);
  const handleDisplay = () => {
    setIsShow((isShow) => !isShow);
  };
  const handleClick = useCallback(
    (e) => {
      if (count < 10) {
        setCount((count) => count + 1);
      }
    },
    [count]
  );
  const handleAdd = useCallback(() => {
    setArray((prevArray) => {
      if (prevArray.some((item) => item === text)) {
        alert("同じのはだめ");
        return prevArray;
      }
      const newArray = [...prevArray, text];
      return newArray;
    });
  }, [text]);
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      {/* <Header /> */}
      {isShow ? <h1>{count} </h1> : null}
      {/* <button onClick={handleDisplay}>{isShow ? "非表示" : "表示"}</button> */}
      <div style={{ textAlign: "center" }}>
        <input type="text" value={text} onChange={handleChange} />
        <button onClick={handleAdd}>追加</button>
        <ul>
          {array.map((item) => {
            return <div key={item}>{item}</div>;
          })}
        </ul>
        <button onClick={handleClick}>ボタン</button>
      </div>
      {/* <Main title="Index" page="index" /> */}
    </>
  );
}
